# source 'https://github.com/CocoaPods/Specs.git'
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

def pods
	pod "MFNetAPIClient", :path => "../"
end

target 'MFNetAPIClient' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MFNetAPIClient

  pods

  target 'MFNetAPIClientTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
